<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
class ItemType extends Migration
{


   public function defaultData():array{
       return $item_type = array(
        array('id' => '46','category_id' => '3n4hSco1','subcategory_id' => 'zouyFkEx57hGSQt40gsl','type_id' => 'kjG4aQPWdXyRcHDIYSfo6zvOVwEUr5AhmBK2xqTe','type_name' => 'whole milk','type_img'=>'usage/images/itemimg/wefdn26M2GRd.jpg','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => '9','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '47','category_id' => '3n4hSco1','subcategory_id' => 'zouyFkEx57hGSQt40gsl','type_id' => 'mXHtphkWe4rSicV8Y973jPB0R6T5aQSJzo2xqMLf','type_name' => 'low fat milk','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => '18','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '48','category_id' => '3n4hSco1','subcategory_id' => 'zouyFkEx57hGSQt40gsl','type_id' => 'hAosxTQNfPLuY3iVM76IgzOt9b1dC5cljWH0wvR8','type_name' => 'skimmed milk','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => '16','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '49','category_id' => '3n4hSco1','subcategory_id' => 'zouyFkEx57hGSQt40gsl','type_id' => 'XB3rLGIRDP46mStHaz9QUF7q5kMeE0Y2TcWOuw1g','type_name' => 'raw milk','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => '','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '53','category_id' => '3n4hSco1','subcategory_id' => 'mk09TpAaHFItxdg51wGi','type_id' => 'iqBNg9SIprH1wRMoh6DUKcbOx0dE2LjGzTlvSYfn','type_name' => 'Cottage cheese','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '54','category_id' => '3n4hSco1','subcategory_id' => 'mk09TpAaHFItxdg51wGi','type_id' => 'ltiFhSwkmxBORqd5QpYWCGDU7TA2HKgJPouXynS9','type_name' => 'Fresh cheese','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '55','category_id' => '3n4hSco1','subcategory_id' => 'mk09TpAaHFItxdg51wGi','type_id' => 'Sa8fbwGmOLu9BK6AzCVJh4UdXg7eP1Hqikr2jnRD','type_name' => 'Cream cheese','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '56','category_id' => '3n4hSco1','subcategory_id' => 'mk09TpAaHFItxdg51wGi','type_id' => 'OQBv9utj50gMpWV1XnefLCJy2ISAKDscxdYoNGU6','type_name' => 'monterey jac','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '57','category_id' => '3n4hSco1','subcategory_id' => 'mk09TpAaHFItxdg51wGi','type_id' => 'Q6S9RfcO2JSBamhAU5CvbHjG0N1I7xEKpWyoXYus','type_name' => 'Mascarpo','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '58','category_id' => '3n4hSco1','subcategory_id' => 'mk09TpAaHFItxdg51wGi','type_id' => 'xdBq1tS4NFbj0IHQO5eXMpAavwTsU6KJk7rgVPhn','type_name' => 'Ricotta','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '59','category_id' => '3n4hSco1','subcategory_id' => 'mk09TpAaHFItxdg51wGi','type_id' => '7UayuFtGdN513nAgPJlw0RQqL8srkHXifIz9WVSK','type_name' => 'Goat cheese','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '60','category_id' => '3n4hSco1','subcategory_id' => '1AtsXj50WM9bi4vGSfYz','type_id' => 'A3RXOPG59zHf8W2cVYIC','type_name' => 'traditional unstrained yogurt','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => '7','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '61','category_id' => '3n4hSco1','subcategory_id' => '1AtsXj50WM9bi4vGSfYz','type_id' => '2EVkjoAyYtP51Fsa4uXIKvmWpMcJgRLzOUwShi7q','type_name' => 'greek yogurt.','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => '','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '62','category_id' => '3n4hSco1','subcategory_id' => '1AtsXj50WM9bi4vGSfYz','type_id' => 'BiV48gDXpHsTI63N0oPyrJR1mzFSt7UfKWC2kMul','type_name' => 'goat milk yogurt','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => '','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '63','category_id' => '3n4hSco1','subcategory_id' => '1AtsXj50WM9bi4vGSfYz','type_id' => '2F5YBdWbEwmKLN6s1ekVMTCypuHgt8QXUGlS3v9n','type_name' => 'sheep&#039;s milk yogurt','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => '','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '64','category_id' => '3n4hSco1','subcategory_id' => '1AtsXj50WM9bi4vGSfYz','type_id' => 'sywAgUEdq6zDaKJkpIfGcoNhmLQXn2x1WHSVeYlv','type_name' => 'skyr, aka icelandic yogurt','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => '','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '65','category_id' => '3n4hSco1','subcategory_id' => '1AtsXj50WM9bi4vGSfYz','type_id' => '0S9zjShC34wymOAPJvbUfTpxHXlL5oduMGqWg6VY','type_name' => 'australian yoghurt','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => '','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '66','category_id' => '3n4hSco1','subcategory_id' => '1AtsXj50WM9bi4vGSfYz','type_id' => 'g48jJSXVDps63FdhlxHGAzfIubS7mC9UqNOkvK1e','type_name' => 'soy yogurt','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => '','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '67','category_id' => '3n4hSco1','subcategory_id' => '1AtsXj50WM9bi4vGSfYz','type_id' => 'aj4IQgXRz2yVhNTUOSn1MCBwoYu0pleWqAf5G7cL','type_name' => 'almond yogurt','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '3.2','max_price' => '5.8','expiring_date' => '7','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '68','category_id' => 'uhGfQKrg','subcategory_id' => '2lWgs49FvDCyirjAn5MH','type_id' => 'IGd8azwTlXkt7DM0ScoORNCvnFgEuWbKy4rxLV6S','type_name' => ' white grapefruit','type_img'=>'usage/images/itemimg/','type_des' => NULL,'min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '69','category_id' => 'uhGfQKrg','subcategory_id' => '2lWgs49FvDCyirjAn5MH','type_id' => 'EhajDWXeg0iBPJtI2QTcSyFCOod3SzGu854AvmsR','type_name' => 'sweeties grapefruit','type_img'=>'usage/images/itemimg/','type_des' => NULL,'min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '70','category_id' => 'uhGfQKrg','subcategory_id' => '2lWgs49FvDCyirjAn5MH','type_id' => 'lnFNLcQWE8YJfe0K2Cyt5vGphgOMoB9ka6smbxjI','type_name' => 'red grapefruit','type_img'=>'usage/images/itemimg/','type_des' => NULL,'min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '71','category_id' => 'uhGfQKrg','subcategory_id' => '2lWgs49FvDCyirjAn5MH','type_id' => 'r2u18BHA7fCSlYSmUsXP6qIVNDG3L0cwax45EWth','type_name' => 'pink grapefruit','type_img'=>'usage/images/itemimg/','type_des' => NULL,'min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '72','category_id' => 'uhGfQKrg','subcategory_id' => 'Vuh08M4qtrHUy26YKPpi','type_id' => 'oyI0mUtxaHSgN6uiRJM1XKfTdlqEVLvC7c4Q5P2h','type_name' => 'navel orange','type_img'=>'usage/images/itemimg/','type_des' => NULL,'min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '73','category_id' => 'uhGfQKrg','subcategory_id' => 'Vuh08M4qtrHUy26YKPpi','type_id' => 'SuARO8cJiwCM2VjThUbPpnmLrs7yGq43gB6kYQ01','type_name' => 'blood orange','type_img'=>'usage/images/itemimg/','type_des' => NULL,'min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '74','category_id' => 'uhGfQKrg','subcategory_id' => 'Vuh08M4qtrHUy26YKPpi','type_id' => 'GanKkjUrwhoQYJ9Tt71z6P4ReIWylxgNDpO3CiuF','type_name' => 'mandarin orange','type_img'=>'usage/images/itemimg/','type_des' => NULL,'min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '75','category_id' => 'uhGfQKrg','subcategory_id' => 'Vuh08M4qtrHUy26YKPpi','type_id' => 'tX9STvgeh6uyG25nP1LsIkzpWBrQUF7NmxEbi03H','type_name' => 'tangerine','type_img'=>'usage/images/itemimg/','type_des' => NULL,'min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '76','category_id' => 'uhGfQKrg','subcategory_id' => 'Vuh08M4qtrHUy26YKPpi','type_id' => '4cCBSvtMrnR7dowyEYUF8Sij9xfu21W6sGOmNelQ','type_name' => 'clementine','type_img'=>'usage/images/itemimg/','type_des' => NULL,'min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '77','category_id' => 'uhGfQKrg','subcategory_id' => 'OLBxCusSdib2JDfXP3eU','type_id' => 'HvyolpBLeiSAmdVtfrnOWNICR5q7TDgaS6zX1GEY','type_name' => 'amboisa','type_img'=>'usage/images/itemimg/Xfj9chMm4S9F.jpg','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => '60','fraction' => '0.134','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '78','category_id' => 'uhGfQKrg','subcategory_id' => 'OLBxCusSdib2JDfXP3eU','type_id' => 'FnyYaHmwS6UQgMfjG4uNz3RD7kp5b1PsJIWCq9iT','type_name' => 'cortland','type_img'=>'usage/images/itemimg/XdseVsT5ickG.jpg','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => '','fraction' => '0.134','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '79','category_id' => 'uhGfQKrg','subcategory_id' => 'OLBxCusSdib2JDfXP3eU','type_id' => 'XHChVtdvkKYD3BIn6FfJoTPie27MRNyQEjxsg4cG','type_name' => 'winesap','type_img'=>'usage/images/itemimg/9mbbehsAinH1.jpg','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => '','fraction' => '0.134','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '80','category_id' => 'uhGfQKrg','subcategory_id' => 'OLBxCusSdib2JDfXP3eU','type_id' => 'UTJM5DaVmtYEQ71pdBo2rKSXl6bLWnOSFqcyPAwi','type_name' => 'goldspur','type_img'=>'usage/images/itemimg/of2DZS3o4YnM.jpg','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => '','fraction' => '0.134','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '81','category_id' => 'uhGfQKrg','subcategory_id' => '3vlyDWzAKabjmfpLNYMo','type_id' => 'FfqcnKw9DgY5S3X8uTit','type_name' => 'abacaxi pineapples','type_img'=>'usage/images/itemimg/h929Se2IJbns.jpg','type_des' => 'Abacaxi pineapples are very sweet and quite resistant to disease, making them a very popular crop to grow. They weigh anywhere from two to eleven pounds. They&rsquo;re spiny and tall, and their flesh is nearly translucent in color. They&rsquo;re delicious, but too delicate for commercial purposes','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '82','category_id' => 'uhGfQKrg','subcategory_id' => '3vlyDWzAKabjmfpLNYMo','type_id' => 'n0clRfg8SUdN1TVrby2i','type_name' => ' smooth cayenne pineapples','type_img'=>'usage/images/itemimg/jGS65DM20uAV.jpg','type_des' => 'They fyellow flesh and are very juicy pineappple.','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '83','category_id' => 'uhGfQKrg','subcategory_id' => '9wUg1sqTtQYG2b6WmVnC','type_id' => '9Uq2H1QNgEjpxAorRduizk8VFSf6KJBIPl4yMYcm','type_name' => 'seedless watermelons','type_img'=>'usage/images/itemimg/','type_des' => NULL,'min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '84','category_id' => 'uhGfQKrg','subcategory_id' => '9wUg1sqTtQYG2b6WmVnC','type_id' => 'DQmJAlatv54PRCFoEGeYnbMK3V8w7izWhSTrN2kO','type_name' => 'picnic','type_img'=>'usage/images/itemimg/','type_des' => NULL,'min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '85','category_id' => 'uhGfQKrg','subcategory_id' => '9wUg1sqTtQYG2b6WmVnC','type_id' => 'qASzKmPRXMjilwJNdLT9k8fGst4Q5rBvy3g1EHeW','type_name' => ' icebox','type_img'=>'usage/images/itemimg/','type_des' => NULL,'min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '86','category_id' => 'uhGfQKrg','subcategory_id' => '9wUg1sqTtQYG2b6WmVnC','type_id' => 'vYMLIuAdqTVOEDW89rHQz73PGblNpcsFmC6yS4Rx','type_name' => 'yellow/orange','type_img'=>'usage/images/itemimg/','type_des' => NULL,'min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '87','category_id' => 'uhGfQKrg','subcategory_id' => 'f8gh2mL35BxWboTSa4jM','type_id' => 'Vbzmry7wodXH0qU6KE4xWSj3TlfpktABcMS2CsnI','type_name' => 'red pawpaw','type_img'=>'usage/images/itemimg/SnsAI2MjEdFa.jpg','type_des' => NULL,'min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '88','category_id' => 'uhGfQKrg','subcategory_id' => 'f8gh2mL35BxWboTSa4jM','type_id' => 'YlotWKANcv6a4GMRgD0yn7HQFP8e3hJzBjSidfL1','type_name' => 'yellow pawpaw','type_img'=>'usage/images/itemimg/KbeydGMW9hhT.jpg','type_des' => NULL,'min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '89','category_id' => 'uhGfQKrg','subcategory_id' => 'HcvaNO36MgRGr12DYj4J','type_id' => '0PoKQDv9bSeHAuY6qRF8','type_name' => 'solanum melongena','type_img'=>'usage/images/itemimg/jAsaW99UMrdd.jpg','type_des' => 'Pear shaped, purple and 9 inches long','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '90','category_id' => 'uhGfQKrg','subcategory_id' => 'HcvaNO36MgRGr12DYj4J','type_id' => 'ACKbDfEVouS9BsqjXJLr','type_name' => 'indian eggplant','type_img'=>'usage/images/itemimg/Xd2de9jmDYA1.jpg','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '91','category_id' => 'uhGfQKrg','subcategory_id' => 'HcvaNO36MgRGr12DYj4J','type_id' => '1chVknelFpmAXOtUjRIQ','type_name' => 'white varieties','type_img'=>'usage/images/itemimg/Fnsdjg3KYdfO.jpg','type_des' => 'These garden eggs are white and are round','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '92','category_id' => 'uhGfQKrg','subcategory_id' => 'HcvaNO36MgRGr12DYj4J','type_id' => 'yRkNwbmcMWLAtVU5X6Ss','type_name' => 'ghostbuster','type_img'=>'usage/images/itemimg/nAyoFctGE9U2.jpg','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '93','category_id' => 'uhGfQKrg','subcategory_id' => 'HcvaNO36MgRGr12DYj4J','type_id' => 'oIBkmiyhK18DxqdpsnLg','type_name' => 'green local','type_img'=>'usage/images/itemimg/cod53mQgw6eG.jpg','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '94','category_id' => '3n4hSco1','subcategory_id' => 'zouyFkEx57hGSQt40gsl','type_id' => 'No3UjuHnxAdP4SMh6iDs','type_name' => '','type_img'=>'usage/images/itemimg/','type_des' => '','min_price' => '0','max_price' => '0','expiring_date' => '25','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '95','category_id' => 'DyOqxeIM','subcategory_id' => 'j24ME5aJXCdeOUPNzV6y','type_id' => 'yktC7ze6RsNFjJLAQcT8GSvnworPSfhaUWb2i0xm','type_name' => 'white fulani cattle','type_img'=>'usage/images/itemimg/JARV1cjdYdK9.jpg','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '96','category_id' => 'DyOqxeIM','subcategory_id' => 'j24ME5aJXCdeOUPNzV6y','type_id' => 'QAzdNTRM0gCJ1KXIh7Ut5HbS9f2p6YWyxkvq4Gmc','type_name' => 'red fulani cattle','type_img'=>'usage/images/itemimg/Sg9A2iVSdIUh.jpg','type_des' => '','min_price' => '1','max_price' => '2','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '97','category_id' => 'DyOqxeIM','subcategory_id' => 'j24ME5aJXCdeOUPNzV6y','type_id' => 'Uxg2CraTunFtNRdSeikG','type_name' => 'ndama','type_img'=>'usage/images/itemimg/m0bcSh02jdjg.jpg','type_des' => '','min_price' => '120.4','max_price' => '300.1','expiring_date' => NULL,'fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '98','category_id' => 'iNOM0SuJ','subcategory_id' => 'kKXRYOMHGvfynie1bt6N','type_id' => '6bjFJgSxy2rhzECfRq85','type_name' => 'white rice','type_img'=>'usage/images/itemimg/nPdjqc02Maf6.jpg','type_des' => 'White rice is milled rice that has had its husk, bran, and germ removed. This alters the flavor, texture and appearance of the rice and helps prevent spoilage and extend its storage life. After milling, the rice is polished, resulting in a seed with a bright, white, shiny appearance','min_price' => '0.22','max_price' => '0.62','expiring_date' => '180','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '99','category_id' => 'iNOM0SuJ','subcategory_id' => 'kKXRYOMHGvfynie1bt6N','type_id' => 'VSbLNcsRiJXYWnSAU7vr','type_name' => 'brown rice','type_img'=>'usage/images/itemimg/22HdXdWo97Sg.jpg','type_des' => '','min_price' => '0.37','max_price' => '0.72','expiring_date' => '100','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '100','category_id' => 'iNOM0SuJ','subcategory_id' => 'kKXRYOMHGvfynie1bt6N','type_id' => '7xIfA2TXhglq0bMosmtC','type_name' => 'ofada','type_img'=>'usage/images/itemimg/erOMftisn1do.jpg','type_des' => '','min_price' => '0.45','max_price' => '0.56','expiring_date' => '78','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '101','category_id' => '8BqzE4tWji9X','subcategory_id' => 'rLSxUSjC37GeO4ynbvPm','type_id' => 'R7XD5IBNtSK28C6YdH49','type_name' => 'red onion','type_img'=>'usage/images/itemimg/nh9rIRW7sdjV.jpg','type_des' => 'Red onions are cultivars of the onion with purplish-red skin and white flesh tinged with red. These onions tend to be medium to large in size and have a mild flavor. They are often consumed raw, grilled or lightly cooked with other foods, or added as a decoration to salads','min_price' => '0.27','max_price' => '0.46','expiring_date' => '32','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '102','category_id' => 'iNOM0SuJ','subcategory_id' => 'zPCLhHj2WxwukB13mDXA','type_id' => '5dFhRe9sJGAI3rqSHyMo','type_name' => 'white beans','type_img'=>'usage/images/itemimg/HYYHjbDcSSnb.jpeg','type_des' => 'White beans is a variety of the common bean native to the sother people of Nigeria where it was domesticated. It is a small, dry white bean which is smaller than many other types of white beans, and has an oval, slightly flattened shape.It is claimed to be the most protanacious of all bean.','min_price' => '0.23','max_price' => '0.46','expiring_date' => '55','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '103','category_id' => 'iNOM0SuJ','subcategory_id' => 'zPCLhHj2WxwukB13mDXA','type_id' => 'H8caeQC9dhOwGzp0q4AS','type_name' => 'brown bean','type_img'=>'usage/images/itemimg/ejyRfHHhdIi2.jpeg','type_des' => 'Brown bean  is the most popular bean in Nigeria and is most often eaten whole, or mashed and then refried. Either way, it is a common filling for most cuisine.','min_price' => '0.36','max_price' => '0.56','expiring_date' => '66','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '104','category_id' => 'iNOM0SuJ','subcategory_id' => 'zPCLhHj2WxwukB13mDXA','type_id' => 'WPxRn4G3yjO0U5Et1l7T','type_name' => 'green beans','type_img'=>'usage/images/itemimg/KaonM9DTnFdd.jpeg','type_des' => 'Green beans, also known as string bean, snap bean in the northeastern and western United States, are the unripe fruit of various cultivars of the common bean (Phaseolus vulgaris). Haricots verts, French for &quot;green beans&quot;, also known as French beans, French green beans, French filet beans, is a The variety of green bean that&#039;s longer, thinner, crisp, and tender. They are collected tender and eaten as a vegetable; the whole fruit (pod and the seeds) are eaten. Over 130 varieties of green bean are known. Varieties specialized for use as green beans, are selected for the succulence and flavor of their pods. They are usually grown in the home vegetable garden, and many varieties exist. It&rsquo;s used in many food recipes all over the world','min_price' => '0.5','max_price' => '4','expiring_date' => '45','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '105','category_id' => 'mG3huSN8','subcategory_id' => 'DX2RKwHOpEuqTdx94oga','type_id' => 'zbS7STPQIdmrHxX94V6p','type_name' => 'seed','type_img'=>'usage/images/itemimg/rdhMShnQHeKb.png','type_des' => 'The peanut, also known as the groundnut,  and taxonomically classified as Arachis hypogaea, is a legume crop grown mainly for its edible seeds. It is widely grown in the tropics and subtropics, being important to both small and large commercial producers','min_price' => '1.2','max_price' => '4.6','expiring_date' => '15','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '106','category_id' => 'mG3huSN8','subcategory_id' => 'DX2RKwHOpEuqTdx94oga','type_id' => 'JCESWzgd156QUxFRYVO4','type_name' => 'shell','type_img'=>'usage/images/itemimg/cGZ2cWeJK5b2.jpeg','type_des' => 'The peanut, also known as the groundnut,  and taxonomically classified as Arachis hypogaea, is a legume crop grown mainly for its edible seeds. It is widely grown in the tropics and subtropics, being important to both small and large commercial producers','min_price' => '2.1','max_price' => '3.8','expiring_date' => '14','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '107','category_id' => 'cXYnlzmi2oJy','subcategory_id' => '59uLnSBCXwTV6YRatrzk','type_id' => 'FnXfrlCz1TVc98ymAkvh','type_name' => 'cat fish','type_img'=>'usage/images/itemimg/rZHhSy952SAd.png','type_des' => 'Catfish are a diverse group of ray-finned fish. Named for their prominent barbels, which resemble a cat&#039;s whiskers, catfish range in size and behavior from the three largest species alive','min_price' => '2','max_price' => '6','expiring_date' => '30','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '108','category_id' => 'cXYnlzmi2oJy','subcategory_id' => '59uLnSBCXwTV6YRatrzk','type_id' => 'fWHtbmj9NQpglK7SU3oC','type_name' => 'tilapia','type_img'=>'usage/images/itemimg/H5AtVk27jJ3j.jpg','type_des' => 'Tilapia is the common name for nearly a hundred species of cichlid fish from the coelotilapine, coptodonine, heterotilapine, oreochromine, pelmatolapiine and tilapiine tribes, with the economically most important species placed in Coptodonini and Oreochromi','min_price' => '3','max_price' => '8','expiring_date' => '30','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '109','category_id' => 'cXYnlzmi2oJy','subcategory_id' => '59uLnSBCXwTV6YRatrzk','type_id' => 'SUWNeXVzdybFG8sm3rKt','type_name' => 'croker','type_img'=>'usage/images/itemimg/XA3dUi5tH3SH.jpg','type_des' => 'croaker is a species of marine ray-finned fish belonging to the family Sciaenidae and is closely related to the black drum, the silver perch, the spot croaker, the red drum, the spotted seatrout, and the weakfish','min_price' => '4','max_price' => '9','expiring_date' => '30','fraction' => '0.078','agg_frac' => '0.001','war_frac' => '0.001','vat_frac' => '0.075','isp_frac' => '0.055','log_frac' => '0.001','proli_frac' => '0.001'),
        array('id' => '110','category_id' => 'LP5cWb0oe9Jj','subcategory_id' => 'DP4Ry9VXsFJSjQT6ac5h','type_id' => 'b7da1NEX8fiOM3gTVFPA2rkeWvCs9LyxtSYq4n5J','type_name' => 'green tea','type_img'=>'usage/images/itemimg/dAa5HYVP1sGF.png','type_des' => 'Tea is an aromatic beverage prepared by pouring hot or boiling water over cured or fresh  tea leaves. Tea is rich in polyphenols, which are natural compounds that have health benefits, such as reducing inflammation and helping to fight cancer.These substances can reduce the formation of free radicals in the body, protecting cells and molecules from damage. These free radicals play a role in aging and many types of diseases. ','min_price' => '40','max_price' => '280','expiring_date' => '180','fraction' => '0.196','agg_frac' => '0.011','war_frac' => '0.04','vat_frac' => '0.075','isp_frac' => '0.04','log_frac' => '0.02','proli_frac' => '0.01'),
        array('id' => '111','category_id' => '8BqzE4tWji9X','subcategory_id' => 'e65jyOPHTFa7t3J8XSpg','type_id' => 'ErLc3Q8Rx2jloNq5fzXP','type_name' => 'bell papper','type_img'=>'usage/images/itemimg/HFWD5cD3iQon.jpg','type_des' => 'Red, Orange, Green and Yellow Bell Peppers are full of great health benefits they&#039;re packed with vitamins and low in calories! They are an excellent source of vitamin A, vitamin C, and potassium. Bell Peppers also contain a healthy dose of fiber, folate, and iron','min_price' => '2','max_price' => '5','expiring_date' => '7','fraction' => '0.091','agg_frac' => '0.01','war_frac' => '0.001','vat_frac' => '0','isp_frac' => '0.06','log_frac' => '0.01','proli_frac' => '0.01'),
        array('id' => '112','category_id' => '8BqzE4tWji9X','subcategory_id' => 'e65jyOPHTFa7t3J8XSpg','type_id' => 'ApUCLuxRsiXNybTMhHWmokFV7lr3cOaK9GED2v4q','type_name' => 'chilli peper','type_img'=>'usage/images/itemimg/uIZjsYDUYVgj.png','type_des' => 'Health benefits of Chili pepper includes improves digestive health and metabolism, alleviates migraines, may reduce risks of cancer, fights fungal infections, colds, and the flu, provides joint pain relief, fights inflammation, supports cardiovascular health, may improve cognitive functions, may improve longevity, promotes red blood cell growth, improve ocular health and keeps your hair and skin healthy and more','min_price' => '0.5','max_price' => '30','expiring_date' => '7','fraction' => '0.179','agg_frac' => '0.01','war_frac' => '0.01','vat_frac' => '0.075','isp_frac' => '0.064','log_frac' => '0.01','proli_frac' => '0.01'),
        array('id' => '113','category_id' => '8BqzE4tWji9X','subcategory_id' => 'kQd3OiaX8TnfAwypmqEx','type_id' => 'L3XGm8pVDwUYfOsNWJAF','type_name' => 'galiic','type_img'=>'usage/images/itemimg/6AnjYAe0FPDM.jpg','type_des' => 'Garlic is a plant in the onion family that&rsquo;s grown for its distinctive taste and health benefits. It contains sulfur compounds, which are believed to bring some of the health benefits.Garlic is low in calories and rich in vitamin C, vitamin B6 and manganese. It also contains trace amounts of various other nutrients.Garlic supplements help prevent and reduce the severity of common illnesses like the flu and common cold','min_price' => '1','max_price' => '10','expiring_date' => '40','fraction' => '0.175','agg_frac' => '0.01','war_frac' => '0.01','vat_frac' => '0.075','isp_frac' => '0.06','log_frac' => '0.01','proli_frac' => '0.01'),
        array('id' => '114','category_id' => '8BqzE4tWji9X','subcategory_id' => 'foBIAD8RlpcPEXN2qsLU','type_id' => 'z8NTM1weAXqKyYlkRsS3','type_name' => 'ginger','type_img'=>'usage/images/itemimg/TKJ9dyqaGXRd.jpg','type_des' => 'Ginger has a very long history of use in various forms of traditional and alternative medicine. It&rsquo;s been used to aid digestion, reduce nausea, and help fight the flu and common cold,','min_price' => '0.5','max_price' => '10','expiring_date' => '30','fraction' => '0.179','agg_frac' => '0.01','war_frac' => '0.01','vat_frac' => '0.075','isp_frac' => '0.064','log_frac' => '0.01','proli_frac' => '0.01')
      );
      
   } 
    /**
     * Run the migrations.
     *
     * @return void
     */
    public  function insertData():bool{
       
        try {
            DB::table('item_type')->insert($this->defaultData());
            return true;
        } catch (\Throwable $th) {
            return false;
            //throw $th;
        }
     } 
    public function up()
    {   if(Schema::hasTable('item_type')) return; 
        Schema::create('item_type', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('category_id',64)->default(NULL);
            $table->string('subcategory_id',120)->default(NULL);
            $table->string('type_id',120)->default(NULL);
            $table->string('type_name',120)->default(NULL);
            $table->string('type_img',120)->default(NULL);
            $table->text('type_des')->nullable()->default(NULL);
            $table->double('min_price',12, 2);
            $table->double('max_price', 12, 2);
            $table->string('expiring_date')->nullable()->default(NULL);
            $table->double('fraction', 12, 2)->default(0.01);
            $table->double('agg_frac', 12, 2)->default(0.01);
            $table->double('war_frac', 12, 2)->default(0.01);
            $table->double('vat_frac', 12, 2)->default(0.01);
            $table->double('isp_frac', 12, 2)->default(0.01);
            $table->double('log_frac', 12, 2)->default(0.01);
            $table->double('proli_frac', 12, 2)->default(0.01);
            //$table->double('hub_frac', 12, 2)->default(0.01);
            
        });
          $this->insertData();

    
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('item_type');
    }
}
